### ISSUE TITLE
Fail to fetch error on blueprint planning.

### ISSUE THREAD

**Issue by keatesc** [joelverhagen/FactorioTools#3]
Great util, glad I found it.

Today I've started receiving the following error:

```
TypeError: Failed to fetch
    at Ba.customFetch (https://factorio-tools.vercel.app/assets/index-9fb5e1c4.js:9:27393)
    at Ba.request (https://factorio-tools.vercel.app/assets/index-9fb5e1c4.js:9:28692)
    at Object.v1OilFieldPlanCreate (https://factorio-tools.vercel.app/assets/index-9fb5e1c4.js:9:29879)
    at ka (https://factorio-tools.vercel.app/assets/index-9fb5e1c4.js:9:31615)
    at Proxy.submit (https://factorio-tools.vercel.app/assets/index-9fb5e1c4.js:9:77134)
    at https://factorio-tools.vercel.app/assets/index-9fb5e1c4.js:9:80365
    at https://factorio-tools.vercel.app/assets/index-9fb5e1c4.js:1:55309
    at mt (https://factorio-tools.vercel.app/assets/index-9fb5e1c4.js:1:14052)
    at qe (https://factorio-tools.vercel.app/assets/index-9fb5e1c4.js:1:14130)
    at HTMLButtonElement.n (https://factorio-tools.vercel.app/assets/index-9fb5e1c4.js:1:51894)
```

Associated blue print attached.

I'm dicking around in a sandbox game, and hand 'built' the oilfield with console commands. I've done this before and used the planner without issue, as well as with larger oilfields with more pumpjacks.

[oilfield_bp.txt](https://github.com/joelverhagen/FactorioTools/files/13468382/oilfield_bp.txt)

**Comment by joelverhagen** [comment]
Thanks for the heads up. I've fixed the bug. Give it a try!
